puts("The students of my cohort at Makers Academy")
puts("---------------------")
puts("Enrique Comba Riepenhausen")
puts("Stephen Lloyd")
puts("Alex Peattie")
puts("vic329")
puts("NicolePell")
puts("Bernard")
puts("elenagarrone")
puts("Yvette Cook")
puts("Stephen Giles")
puts("Ana Isabel Nogal")
puts("craigh44")
puts("Tim Scully")
puts("Ella Schofield")
puts("Fadie H")
puts("mala23")

print "Overall, we have "
print 15
puts(" great students")
